---

version: "3"

services:
  accounts:
    build:
      context: .
      dockerfile: Dockerfile-development
    network_mode: host
    volumes:
      - ./assets:/opt/accounts/assets
      - ./config:/opt/accounts/config
      - ./lib:/opt/accounts/lib
      - ./priv:/opt/accounts/priv
      - ./test:/opt/accounts/test
    command: do ecto.create, phx.server
    working_dir: /opt/accounts
    depends_on:
      - postgres

  postgres:
    image: timescale/timescaledb:latest-pg11
    network_mode: host
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
