# Dockerfile
# A dockerfile for accounts development

FROM elixir:alpine

RUN mkdir -p /opt/accounts

COPY . /opt/accounts
WORKDIR /opt/accounts

ENV APP_NAME=accounts

RUN apk --no-cache --update add \
  bash git make g++ inotify-tools \
  nodejs nodejs-npm && \
  npm install npm -g --no-progress

RUN cd /opt/accounts && \
  mix local.hex --force && \
  mix local.rebar --force && \
  mix deps.get --all && \
  cd /opt/accounts/assets && \
  npm ci

EXPOSE 4000

ENTRYPOINT ["mix"]
CMD ["phx.server"]
