name: CI

on:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
    push:
        branches:
            - main

jobs:
    CodeQL:
        runs-on: ubuntu-latest

        permissions:
            actions: read
            contents: read
            security-events: write

        strategy:
            fail-fast: false
            matrix:
                language:
                    - javascript

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Initialize
              uses: github/codeql-action/init@v1
              with:
                  languages: ${{ matrix.language }}

            - name: Setup (Node)
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: npm

            - name: Install (Npm)
              run: npm ci

            - name: Build
              run: npm run production

            - name: Analyze
              uses: github/codeql-action/analyze@v1

    Format:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup (Node)
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: npm

            - name: Install (Npm)
              run: npm ci

            - name: Format
              run: node_modules/.bin/prettier --check .

    Test:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql/mysql-server:8.0
                ports:
                    - 3306:3306
                environment:
                    MYSQL_ALLOW_EMPTY_PASSWORD: 1
                    MYSQL_DATABASE: accounts
                    MYSQL_ROOT_PASSWORD: mysql

            redis:
                image: redis:alpine
                ports:
                    - 6379:6379

            meilisearch:
                image: getmeili/meilisearch:latest
                ports:
                    - 7700:7700

            mailhog:
                image: mailhog/mailhog:latest
                ports:
                    - 1025:1025
                    - 8025:8025

            selenium:
                image: selenium/standalone-chrome

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup (Php)
              uses: shivammathur/setup-php@v2
              with:
                  tools: composer
                  php-version: "8.0"

            - name: Setup (Node)
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: npm

            - name: Configure (Env)
              run: php -r "file_exists('.env') || copy('.env.example', '.env');"

            - name: Install (Composer)
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

            - name: Install (Npm)
              run: npm ci

            - name: Configure (Key)
              run: php artisan key:generate

            - name: Test
              run: vendor/bin/phpunit
              env:
                  SCOUT_DRIVER: meilisearch
                  MEILISEARCH_HOST: http://127.0.0.1:7700
